# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenturl',
            old_name='content_url',
            new_name='url',
        ),
    ]
